spring.application.name=Election Application

# MVC configuration
spring.mvc.hiddenmethod.filter.enabled = true

# Base configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/election_app?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=adolf23112004
logging.level.org.hibernate.persister.entity=ERROR

# Email Sender configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nikatanasov22@gmail.com
spring.mail.password=dytp xhnf uawk ozww
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
